version: '3.2'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
    - "9090:9090"
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor

  service:
    image: eliaskhaldi/sim_ws_v3
    ports:
    - "8080:8080"

  grafana:
    image: grafana/grafana
    ports:
        - "3000:3000"
    volumes:
        - grafana:/var/lib/grafana
    depends_on:
        - prometheus

  cadvisor:
    image: google/cadvisor:latest
    ports:
    - "8081:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - service
  
  #logspout:
    #image: gliderlabs/logspout:latest
    #volumes:
        #- /etc/hostname:/etc/host_hostname:ro
        #- /var/run/docker.sock:/var/run/docker.sock
    #environment:
        #- publish:"8082:80"
    #ports:
    #- "8082:80"    

volumes:
  grafana:
