scrape_configs:
- job_name: cadvisor
  scrape_interval: 1s
  static_configs:
  - targets:
    - "cadvisor:8080"
# Sets the `Authorization` header on every scrape request with the
# configured username and password.
# password and password_file are mutually exclusive.
#basic_auth:
#  [ username: demo ]
#  [ password: demo ]    
