apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: prise
  name: prise
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    io.kompose.service: prise
status:
  loadBalancer: {}
