apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: prise
  name: prise
spec:
  replicas: 1
  selector:
   matchLabels:
    io.kompose.service: prise  
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: prise
    spec:
      containers:
      - env:
        - name: INFLUX_URI
          value: http://influx:8086
        - name: RABBIT_HOST
          value: rabbit
        - name: RABBIT_PASSWORD
          value: guest
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USERNAME
          value: guest
        image: alogo53/prise
        name: prise
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
