apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webdav
  name: webdav
spec:
  containers:
  - image: visity/webdav
    name: webdav
    ports:
    - containerPort: 80
    resources: {}
    #volumeMounts:
    #- mountPath: /var/www
      #name: webdav
  restartPolicy: OnFailure
  #volumes:
  #- name: webdav
    #persistentVolumeClaim:
      #claimName: webdav
status: {}
